### ISSUE TITLE
Implement user delete functionality in OOP.

### ISSUE THREAD

**Issue by JayKandari** [Mspiro/my-php-blog#1]

**Comment by Mspiro** [comment]
![image](https://user-images.githubusercontent.com/32816725/134149450-3334f089-d1b2-4c73-a565-8a81ce55b2f9.png)
![image](https://user-images.githubusercontent.com/32816725/134149674-97cdac42-72a5-4373-afcd-60e01fef085e.png)
I achieve this functionality using a same file for article and user deletion using switch case.
